### ISSUE TITLE
Design The Verification Page

### ISSUE THREAD

**Issue by Kedar200** [iiitv/PollPulse-Android#2]
Objectives:
Convert the Figma design into an XML Layout.
You do not have to create any logistics in Java for verification of OTP. 
Make Sure the XML layout closely matches the Figma design.

**Comment by Tisha187** [comment]
please assign me this issue.

**Comment by Kedar200** [comment]
Okay Assigned to you @Tisha187 .

**Comment by Tisha187** [comment]
@Kedar200  please add the tag of hacktoberfest accepted to this issue.
