### ISSUE TITLE
Design the signup page

### ISSUE THREAD

**Issue by Kedar200** [iiitv/PollPulse-Android#5]
Design the sign up page it's like same as login page but because of the more number of attributes you should add scroll view layout there.

**Comment by praptisharma28** [comment]
please assign me this.

**Comment by Kedar200** [comment]
Okay Assigned to you @praptisharma28

**Comment by Tisha187** [comment]
is the issue still available to be worked on ?

**Comment by Kedar200** [comment]
Not for now. If @praptisharma28  won't be able to submit before October 15th, then you can work on this issue.

**Comment by kushwahanimisha** [comment]
Is this issue available now ?

**Comment by Kedar200** [comment]
yeah you can work on it @kushwahanimisha .
