### ISSUE TITLE
Create The Bottom Navigation Pannel 

### ISSUE THREAD

**Issue by Kedar200** [iiitv/PollPulse-Android#6]
Create the bottom navigation bar on the dashboard page and ensure it is in a working state. You can seek help from this site: https://www.geeksforgeeks.org/bottom-navigation-bar-in-android. It is not necessary to design all the pages, but you can create demo pages for better understanding.

**Comment by Kalpeet-kapse123** [comment]
Hey could you plz assign the issue to me will be happy to contribute

**Comment by Kedar200** [comment]
Okay @Kalpeet-kapse123 assigned to you

**Comment by tushant-akar** [comment]
is the issue still available to be worked on?

**Comment by Kalpeet-kapse123** [comment]
Done
