### ISSUE TITLE
Design the home page

### ISSUE THREAD

**Issue by tushant-akar** [iiitv/PollPulse-Android#9]

**Comment by tushant-akar** [comment]
may you plz assign this issue to me

**Comment by Kedar200** [comment]
@tushant-akar assigned to you

**Comment by tushant-akar** [comment]
#9 Solved

**Comment by tushant-akar** [comment]
@Kedar200 sir plz add hacktoberfest and contributon tag

**Comment by tushant-akar** [comment]
Sir plz mark this issue as closed

**Comment by tushant-akar** [comment]
@Kedar200 plz mark this issue as closed
